In [13]:
import pandas as pd
import numpy as np

In [14]:
export_gm=pd.read_table('Trade_Map_-_List_of_products_exported_by_Germany.txt', sep='\t')
import_gm=pd.read_table('Trade_Map_-_List_of_products_imported_by_Germany.txt', sep='\t')
export_gm.loc[0, 'Code'] = 0 #각 연도별 총액 자료에 활용하기 위해 drop하지 않고 남겨둠
import_gm.loc[0, 'Code'] = 0 #각 연도별 총액 자료에 활용하기 위해 drop하지 않고 
export_gm.drop([export_gm.columns[12]], axis=1, inplace=True) #'Unnamed: 12'열 삭제
import_gm.drop([import_gm.columns[12]], axis=1, inplace=True) #'Unnamed: 12'열 삭제
export_gm['Code']=export_gm['Code'].astype('int64')
import_gm['Code']=import_gm['Code'].astype('int64')

In [15]:
hs17_12_4_bec=pd.read_csv('hs17_12_4_bec.csv')
hs17_12_4_bec

        HS4   HS12    HS17  BEC5Code1
0       101  10121       0     712010
1       101  10129       0       1111
2       101  10130       0       1111
3       101  10190       0       1111
4       102  10221       0     112010
...     ...    ...     ...        ...
10587  9702      0  970200     713202
10588  9703      0  970300     713202
10589  9704      0  970400     813202
10590  9705      0  970500     713202
10591  9706      0  970600     713202

[10592 rows x 4 columns]

In [16]:
amount_gm=pd.merge(export_gm,import_gm,how='outer')
amount_gm.rename(columns={'Code':'HS17'}, inplace=True)#HS코드를 먼저 HS17에 맞춰 merge하기 위해 HS17이라 명명함
amount_gm=pd.merge(amount_gm, hs17_12_4_bec, how='left')

In [17]:
amount_gm.columns

Index(['HS17', 'Product label', 'Exported value in 2012',
       'Exported value in 2013', 'Exported value in 2014',
       'Exported value in 2015', 'Exported value in 2016',
       'Exported value in 2017', 'Exported value in 2018',
       'Exported value in 2019', 'Exported value in 2020',
       'Exported value in 2021', 'Imported value in 2012',
       'Imported value in 2013', 'Imported value in 2014',
       'Imported value in 2015', 'Imported value in 2016',
       'Imported value in 2017', 'Imported value in 2018',
       'Imported value in 2019', 'Imported value in 2020',
       'Imported value in 2021', 'HS4', 'HS12', 'BEC5Code1'],
      dtype='object')

In [18]:
#컬럼 순서 바꾸기
amount_gm=amount_gm[['HS17','HS12', 'HS4', 'BEC5Code1', 'Product label', 'Exported value in 2012',
       'Exported value in 2013', 'Exported value in 2014',
       'Exported value in 2015', 'Exported value in 2016',
       'Exported value in 2017', 'Exported value in 2018',
       'Exported value in 2019', 'Exported value in 2020',
       'Exported value in 2021', 'Imported value in 2012',
       'Imported value in 2013', 'Imported value in 2014',
       'Imported value in 2015', 'Imported value in 2016',
       'Imported value in 2017', 'Imported value in 2018',
       'Imported value in 2019', 'Imported value in 2020',
       'Imported value in 2021']]

In [19]:
amount_gm.isnull().sum()

HS17                        0
HS12                      903
HS4                       903
BEC5Code1                 903
Product label               0
Exported value in 2012     80
Exported value in 2013     80
Exported value in 2014     80
Exported value in 2015     80
Exported value in 2016     80
Exported value in 2017     80
Exported value in 2018     80
Exported value in 2019     80
Exported value in 2020     80
Exported value in 2021     80
Imported value in 2012      8
Imported value in 2013      8
Imported value in 2014      8
Imported value in 2015      8
Imported value in 2016      8
Imported value in 2017      8
Imported value in 2018      8
Imported value in 2019      8
Imported value in 2020      8
Imported value in 2021      8
dtype: int64

In [20]:
no_amount_gm=amount_gm[(amount_gm['Exported value in 2017']==0) 
                       & (amount_gm['Exported value in 2018']==0) 
                       & (amount_gm['Exported value in 2019']==0) 
                       & (amount_gm['Exported value in 2020']==0) 
                       & (amount_gm['Exported value in 2021']==0)
                       & (amount_gm['Imported value in 2017']==0) 
                       & (amount_gm['Imported value in 2018']==0) 
                       & (amount_gm['Imported value in 2019']==0) 
                       & (amount_gm['Imported value in 2020']==0) 
                       & (amount_gm['Imported value in 2021']==0)].index
amount_gm.drop(no_amount_gm, inplace=True)
amount_gm.loc[amount_gm['HS17'] == 0, 'BEC5Code1'] = 000000
amount_gm.loc[amount_gm['HS17'] == 999999, 'BEC5Code1'] = 999999
amount_gm.loc[amount_gm['HS17'] == 999999, 'HS12'] = 999999
amount_gm.loc[amount_gm['HS17'] == 999999, 'HS4'] = 999999

In [21]:
amount_gm.isnull().sum() #2017-2021년 거래가 없는 품목 제외 시 BEC 결측치 22개

HS17                       0
HS12                      22
HS4                       22
BEC5Code1                 22
Product label              0
Exported value in 2012    80
Exported value in 2013    80
Exported value in 2014    80
Exported value in 2015    80
Exported value in 2016    80
Exported value in 2017    80
Exported value in 2018    80
Exported value in 2019    80
Exported value in 2020    80
Exported value in 2021    80
Imported value in 2012     8
Imported value in 2013     8
Imported value in 2014     8
Imported value in 2015     8
Imported value in 2016     8
Imported value in 2017     8
Imported value in 2018     8
Imported value in 2019     8
Imported value in 2020     8
Imported value in 2021     8
dtype: int64

In [22]:
amount_gm[amount_gm['BEC5Code1'].isnull()]

,HS17,HS12,HS4,BEC5Code1,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,...,Imported value in 2012,Imported value in 2013,Imported value in 2014,Imported value in 2015,Imported value in 2016,Imported value in 2017,Imported value in 2018,Imported value in 2019,Imported value in 2020,Imported value in 2021
11014,120792,NaN,NaN,NaN,"Shea nuts """"karite nuts"""", whether or not brok...",0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11146,292422,NaN,NaN,NaN,2-Acetamidobenzoic acid,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11159,262050,NaN,NaN,NaN,Ash and residues containing mainly vanadium,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11445,10120,NaN,NaN,NaN,"Live asses, mules and hinnies",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11446,530521,NaN,NaN,NaN,"Abaca """"Manila hemp or Musa textilis Nee"""", raw""""",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11447,540242,NaN,NaN,NaN,"Filament yarn of polyester, incl. monofilament...",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11448,681260,NaN,NaN,NaN,"Paper, millboard and felt of asbestos or of mi...",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11454,540210,NaN,NaN,NaN,High tenacity filament yarn of nylon or other ...,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11455,530591,NaN,NaN,NaN,Ramie and other vegetable textile fibres n.e.s...,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11457,810710,NaN,NaN,NaN,Unwrought cadmium; powders of cadmium; cadmium...,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11458,540241,NaN,NaN,NaN,"Filament yarn of nylon or other polyamides, in...",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11459,291636,NaN,NaN,NaN,Binapacryl (ISO),NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11460,293010,NaN,NaN,NaN,"Dithiocarbonates """"xanthates""""""""",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11461,293390,NaN,NaN,NaN,Heterocyclic compounds with nitrogen hetero-at...,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11462,293921,NaN,NaN,NaN,Quinine and its salts,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11463,310410,NaN,NaN,NaN,"Carnallite, sylvite and other crude natural po...",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11466,30268,NaN,NaN,NaN,Fresh or chilled toothfish (Dissostichus spp.),NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11469,920910,NaN,NaN,NaN,"Metronomes, tuning forks and pitch pipes",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11470,410721,NaN,NaN,NaN,"Leather of reptiles, vegetable pre-tanned only",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11472,284140,NaN,NaN,NaN,Potassium dichromate,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11477,293792,NaN,NaN,NaN,Oestrogens and progestogens,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11478,540243,NaN,NaN,NaN,"Filament yarn of polyester, incl. monofilament...",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
HS17_BEC_nan_gm=amount_gm[amount_gm['BEC5Code1'].isnull()]

In [24]:
#기존에 merge된 컬럼 삭제하고 HS코드를 HS12에 맞춰 merge하기 위해 HS12이라 명명함
HS17_BEC_nan_gm.drop(['HS12', 'HS4', 'BEC5Code1'],axis=1, inplace=True)
HS17_BEC_nan_gm.rename(columns={'HS17':'HS12'}, inplace=True)

c:\Anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
c:\Anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(