In [29]:
import pandas as pd
import numpy as np

In [30]:
#export 파일 불러오기
export_id=pd.read_table('Trade_Map_-_List_of_products_exported_by_India.txt', sep='\t')
export_id.rename(columns={'Code':'HS'}, inplace=True)
export_id.drop(export_id.index[0], inplace=True)
export_id['HS']=export_id['HS'].astype('int64')

In [31]:
#HS17 코드 불러와서 export 파일과 병합
hs_bec=pd.read_csv('hs_bec17.csv')
export_id=pd.merge(export_id, hs_bec, how='left')

In [32]:
#최근 10년간 거래가 없는 품목 제외시킴
# no_amount_id=export_id[(export_id['Exported value in 2012']==0)
#                        & (export_id['Exported value in 2013']==0) 
#                        & (export_id['Exported value in 2014']==0) 
#                        & (export_id['Exported value in 2015']==0) 
#                        & (export_id['Exported value in 2016']==0) 
#                        & (export_id['Exported value in 2017']==0)  
#                        & (export_id['Exported value in 2018']==0) 
#                        & (export_id['Exported value in 2019']==0) 
#                        & (export_id['Exported value in 2020']==0) 
#                        & (export_id['Exported value in 2021']==0)].index
# export_id.drop(no_amount_id, inplace=True)
#최근 10년간 거래가 없는 품목 제외시킴
no_amount_id=export_id[(export_id['Exported value in 2017']==0)  
                       & (export_id['Exported value in 2018']==0) 
                       & (export_id['Exported value in 2019']==0) 
                       & (export_id['Exported value in 2020']==0) 
                       & (export_id['Exported value in 2021']==0)].index
export_id.drop(no_amount_id, inplace=True)

In [33]:
#HS 999999품목은 따로 묶기 위해 임의의 BEC 번호 999999를 만들어 줌
export_id.loc[export_id['HS'] == 999999, 'BEC17'] = 999999

In [34]:
#BEC17 결측치 확인
export_id[export_id['BEC17'].isnull()]

,HS,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12,BEC17
4992,291470,"Halogenated, sulphonated, nitrated or nitrosat...",64724,77189,79706,86934,74487,9610,0,0,0,0,NaN,NaN
5007,300210,Antisera and other blood fractions and immunol...,40082,57442,47849,45064,86696,17211,0,0,0,0,NaN,NaN
5008,300440,Medicaments containing alkaloids or derivative...,79025,44566,41632,49552,45286,2503,0,0,0,0,NaN,NaN
5028,441232,Plywood consisting solely of sheets of wood <=...,944,193,1239,1140,602,7,0,0,0,0,NaN,NaN
5031,441900,"Tableware and kitchenware, of wood (excluding ...",5247,7486,5662,10135,11758,2777,0,0,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5963,847310,Parts and accessories for typewriters or word-...,3250,46614,9514,6690,3549,45,0,0,0,0,NaN,NaN
5984,600533,"Warp knit fabrics of synthetic fibres, of yarn...",8,2,360,549,568,31,0,0,0,0,NaN,NaN
6006,441890,"Builders' joinery and carpentry, of wood, incl...",636,3074,1647,969,1831,249,0,0,0,0,NaN,NaN
6035,80520,Fresh or dried mandarins incl. tangerines and ...,31,627,356,708,1375,306,0,0,0,0,NaN,NaN
6082,285300,"Inorganic and organic compounds, incl. distill...",5521,3504,3760,1814,1613,881,0,0,0,0,NaN,NaN

In [35]:
#BEC17 결측치 있는 행들만 모아 데이터 프레임을 만듬(아래에서 BEC12 파일과 병합을 위해)
BEC17_nan_id=export_id[export_id['BEC17'].isnull()]

In [36]:
#BEC12 파일과 BEC17 결측치가 담긴 데이터프레임을 병합
hs_bec12=pd.read_csv('hs_bec12.csv')
BEC17_nan_id=pd.merge(BEC17_nan_id, hs_bec12, how='left')

In [37]:
#BEC12와 모두 매치 되어 결측치 없음을 확인
BEC17_nan_id.isnull().sum()

HS                         0
Product label              0
Exported value in 2012     0
Exported value in 2013     0
Exported value in 2014     0
Exported value in 2015     0
Exported value in 2016     0
Exported value in 2017     0
Exported value in 2018     0
Exported value in 2019     0
Exported value in 2020     0
Exported value in 2021     0
Unnamed: 12               64
BEC17                     64
BEC12                      0
dtype: int64

In [38]:
#BEC17_nan_id[BEC17_nan_id['BEC17'].isnull()]

,HS,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12,BEC17,BEC12
0,291470,"Halogenated, sulphonated, nitrated or nitrosat...",64724,77189,79706,86934,74487,9610,0,0,0,0,NaN,NaN,211220
1,300210,Antisera and other blood fractions and immunol...,40082,57442,47849,45064,86696,17211,0,0,0,0,NaN,NaN,711220
2,300440,Medicaments containing alkaloids or derivative...,79025,44566,41632,49552,45286,2503,0,0,0,0,NaN,NaN,711220
3,441232,Plywood consisting solely of sheets of wood <=...,944,193,1239,1140,602,7,0,0,0,0,NaN,NaN,311210
4,441900,"Tableware and kitchenware, of wood (excluding ...",5247,7486,5662,10135,11758,2777,0,0,0,0,NaN,NaN,313202
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,847310,Parts and accessories for typewriters or word-...,3250,46614,9514,6690,3549,45,0,0,0,0,NaN,NaN,611220
60,600533,"Warp knit fabrics of synthetic fibres, of yarn...",8,2,360,549,568,31,0,0,0,0,NaN,NaN,411220
61,441890,"Builders' joinery and carpentry, of wood, incl...",636,3074,1647,969,1831,249,0,0,0,0,NaN,NaN,311210
62,80520,Fresh or dried mandarins incl. tangerines and ...,31,627,356,708,1375,306,0,0,0,0,NaN,NaN,113101
63,285300,"Inorganic and organic compounds, incl. distill...",5521,3504,3760,1814,1613,881,0,0,0,0,NaN,NaN,211220

In [39]:
#BEC4 파일과 BEC12 결측치가 담긴 데이터프레임을 병합하고 결측치 확인
# BEC12_nan_id=BEC17_nan_id[BEC17_nan_id['BEC17'].isnull()]
# hs_bec4=pd.read_csv('hs_bec4.csv')
# BEC12_nan_id=pd.merge(BEC12_nan_id, hs_bec4, how='left')
# BEC12_nan_id.isnull().sum()

HS                         0
Product label              0
Exported value in 2012     0
Exported value in 2013     0
Exported value in 2014     0
Exported value in 2015     0
Exported value in 2016     0
Exported value in 2017     0
Exported value in 2018     0
Exported value in 2019     0
Exported value in 2020     0
Exported value in 2021     0
Unnamed: 12               64
BEC17                     64
BEC12                      0
BEC4                      64
dtype: int64

In [40]:
#BEC17로 채워진 행들(export_id)과 BEC12(BEC17_nan_id)로 채워진 행들을 합치기
export_id_complete=pd.merge(export_id, BEC17_nan_id, how='left')

In [41]:
#컬럼들을 보기 좋게 배열하기 위해 컬럼명 확인
export_id_complete.columns

Index(['HS', 'Product label', 'Exported value in 2012',
       'Exported value in 2013', 'Exported value in 2014',
       'Exported value in 2015', 'Exported value in 2016',
       'Exported value in 2017', 'Exported value in 2018',
       'Exported value in 2019', 'Exported value in 2020',
       'Exported value in 2021', 'Unnamed: 12', 'BEC17', 'BEC12'],
      dtype='object')

In [42]:
export_id_complete=export_id_complete[['HS', 'BEC17', 'BEC12', 'Product label', 'Exported value in 2012',
       'Exported value in 2013', 'Exported value in 2014',
       'Exported value in 2015', 'Exported value in 2016',
       'Exported value in 2017', 'Exported value in 2018',
       'Exported value in 2019', 'Exported value in 2020',
       'Exported value in 2021', 'Unnamed: 12']]

In [43]:
export_id_complete

,HS,BEC17,BEC12,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12
0,271019,213101.0,NaN,"Medium oils and preparations, of petroleum or ...",30189091,46921811,40682152,17629287,16081655,22227429,32327270,29790424,17626804,34867787,NaN
1,710239,411210.0,NaN,"Diamonds, worked, but not mounted or set (excl...",20819464,27084559,22475223,20556917,22437928,22882992,24254392,20575455,14655837,23844452,NaN
2,271012,213101.0,NaN,"Light oils and preparations, of petroleum or b...",0,19765201,19742787,11962340,10664422,12477483,14810618,12646438,8453439,19167099,NaN
3,300490,711220.0,NaN,Medicaments consisting of mixed or unmixed pro...,6631679,8375464,8288881,9327226,9796992,9658816,10782950,12390505,14059367,14718722,NaN
4,711319,413202.0,NaN,"Articles of jewellery and parts thereof, of pr...",17276723,9572682,11222490,7388131,9204800,8371671,11609406,12366518,5678174,8430817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5234,271091,2111.0,NaN,Waste oils containing polychlorinated biphenyl...,0,0,28,0,0,0,1,0,0,0,NaN
5235,370255,611220.0,NaN,"Photographic film, sensitised, in rolls, unexp...",27,40,343,0,0,4,0,2,0,0,NaN
5236,292330,211220.0,NaN,Tetraethylammonium perfluorooctane sulphonate,0,0,0,0,0,3,0,0,0,0,NaN
5237,860390,512020.0,NaN,"Self-propelled railway or tramway coaches, van...",8,40,1,13,831,0,699,746,7114,0,NaN
5238,890392,512.0,NaN,"Motor boats and motor yachts, for pleasure or ...",0,9,0,0,0,524,212,15,101,0,NaN

In [44]:
#BEC17 컬럼과 BEC12 컬럼을 합쳐주기 위해 결측치를 0으로 처리
export_id_complete['BEC17']=export_id_complete['BEC17'].fillna(0)
export_id_complete['BEC12']=export_id_complete['BEC12'].fillna(0)
#BEC17 컬럼과 BEC12 컬럼의 값을 더해서 BEC 컬럼을 만들고 기존의 BEC17 컬럼과 BEC12 컬럼은 제외
export_id_complete['BEC']=export_id_complete['BEC17']+export_id_complete['BEC12']
export_id_complete=export_id_complete.drop(columns=['BEC17','BEC12'])

In [45]:
export_id_complete=export_id_complete[['HS', 'BEC','Product label', 'Exported value in 2012',
       'Exported value in 2013', 'Exported value in 2014',
       'Exported value in 2015', 'Exported value in 2016',
       'Exported value in 2017', 'Exported value in 2018',
       'Exported value in 2019', 'Exported value in 2020',
       'Exported value in 2021', 'Unnamed: 12']]

In [46]:
export_id_complete

,HS,BEC,Product label,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,Exported value in 2020,Exported value in 2021,Unnamed: 12
0,271019,213101.0,"Medium oils and preparations, of petroleum or ...",30189091,46921811,40682152,17629287,16081655,22227429,32327270,29790424,17626804,34867787,NaN
1,710239,411210.0,"Diamonds, worked, but not mounted or set (excl...",20819464,27084559,22475223,20556917,22437928,22882992,24254392,20575455,14655837,23844452,NaN
2,271012,213101.0,"Light oils and preparations, of petroleum or b...",0,19765201,19742787,11962340,10664422,12477483,14810618,12646438,8453439,19167099,NaN
3,300490,711220.0,Medicaments consisting of mixed or unmixed pro...,6631679,8375464,8288881,9327226,9796992,9658816,10782950,12390505,14059367,14718722,NaN
4,711319,413202.0,"Articles of jewellery and parts thereof, of pr...",17276723,9572682,11222490,7388131,9204800,8371671,11609406,12366518,5678174,8430817,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5234,271091,2111.0,Waste oils containing polychlorinated biphenyl...,0,0,28,0,0,0,1,0,0,0,NaN
5235,370255,611220.0,"Photographic film, sensitised, in rolls, unexp...",27,40,343,0,0,4,0,2,0,0,NaN
5236,292330,211220.0,Tetraethylammonium perfluorooctane sulphonate,0,0,0,0,0,3,0,0,0,0,NaN
5237,860390,512020.0,"Self-propelled railway or tramway coaches, van...",8,40,1,13,831,0,699,746,7114,0,NaN
5238,890392,512.0,"Motor boats and motor yachts, for pleasure or ...",0,9,0,0,0,524,212,15,101,0,NaN

In [47]:
export_id_complete.to_csv("export_id.csv", index = False)