In [61]:
import pandas as pd
import numpy as np

In [62]:
vietnam=pd.read_csv('C:/2nd_project/data_set/total_each_country/total_vietnam.csv')
#vietnam=pd.read_csv('C:/2nd_project/data_set/total_each_country/total_vietnam.csv')

In [63]:
vietnam=vietnam.groupby('BEC').sum()
vietnam=vietnam.reset_index()
vietnam=vietnam.astype('int64')
vietnam=vietnam.astype({'BEC':'str'})
vietnam['BEC']= vietnam['BEC'].str.ljust(6, 'x')
vietnam_c1=vietnam[(vietnam['BEC'].str[0]=='1')]
vietnam_c2=vietnam[(vietnam['BEC'].str[0]=='2')]
vietnam_c3=vietnam[(vietnam['BEC'].str[0]=='3')]
vietnam_c4=vietnam[(vietnam['BEC'].str[0]=='4')]
vietnam_c5=vietnam[(vietnam['BEC'].str[0]=='5')]
vietnam_c6=vietnam[(vietnam['BEC'].str[0]=='6')]
vietnam_c7=vietnam[(vietnam['BEC'].str[0]=='7')]
vietnam_c8=vietnam[(vietnam['BEC'].str[0]=='8')]
vietnam_c9=vietnam[(vietnam['BEC'].str[0]=='9')]
vietnam=pd.concat([vietnam_c1,vietnam_c2,vietnam_c3,vietnam_c4,vietnam_c5,vietnam_c6,vietnam_c7,vietnam_c8])

In [64]:
country=[]
for i in range(len(vietnam)):
    country.append('vietnam')
    
vietnam.insert(0,"country",country,True)

In [65]:
vietnam

,country,BEC,Exported value in 2012,Exported value in 2013,Exported value in 2014,Exported value in 2015,Exported value in 2016,Exported value in 2017,Exported value in 2018,Exported value in 2019,...,Imported value in 2012,Imported value in 2013,Imported value in 2014,Imported value in 2015,Imported value in 2016,Imported value in 2017,Imported value in 2018,Imported value in 2019,Imported value in 2020,Imported value in 2021
5,vietnam,1111xx,7131334,6364326,6452053,5162801,5532643,5742643,6129101,5782571,...,3195690,3367664,4367419,4946181,5237489,5439504,6225207,6140080,6895913,7068170
13,vietnam,111210,2381730,2351522,2520978,2972685,2494872,2619941,2797800,2921166,...,6948271,7845972,8105835,8279297,8024537,8000714,8591088,8381669,8453993,9810938
14,vietnam,111220,100715,10661,4274,7052,11440,22603,30598,20538,...,8913,30379,96760,85248,18359,16812,25398,15888,12640,46632
15,vietnam,112010,54338,234834,215276,94730,73455,87726,91208,96888,...,823718,648931,739015,1296394,1112068,1057736,1136272,1184430,1067560,1314072
16,vietnam,113101,13098027,12890834,14884732,14676785,15466569,18394884,18118426,17525091,...,2461792,3079018,3768234,4617879,5465446,7534022,7581637,7865336,7495752,12075522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,vietnam,811220,4194,1734,1900,1822,1809,1743,1367,1065,...,7595,2973,6969,5537,2358,5348,5101,4441,4229,31776
62,vietnam,812020,7606,9803,11147,8191,1439,3630,2741,3299,...,30413,34588,39324,27671,28848,37165,31587,103790,27290,99376
63,vietnam,813101,217,206,227,13,0,0,0,0,...,154,199,218,407,542,612,786,795,1156,1477
64,vietnam,813201,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,455
65,vietnam,813202,8691,9050,9870,6233,7121,7631,10246,20251,...,19574,22828,29139,33938,38599,45553,51682,64401,74649,86029

In [66]:
vietnam.to_csv("vietnam_BEC.csv", index = False)