In [13]:
import pandas as pd
import numpy as np

In [14]:
hs_bec_raw=pd.read_excel('hs_bec.xlsx', sheet_name=[1])
hs_bec_raw=pd.DataFrame(hs_bec_raw[1])
hs_bec_raw

,HS,HS4,HS4Desc,HS6,HS6Desc,BEC5Code1,BEC5Code2,BEC5Category,BEC5EndUse,BEC5Processing,...,GTAPdesc,CPC1,CPCdesc,BEC4Code,BEC4ENDUSE,BEC4INT,BEC4CONS,BEC4CAP,AddedByUNSD,NoteByUNSD
0,H5,101,"Horses, asses, mules and hinnies; live",10121,"Horses; live, pure-bred breeding animals",712010.0,NaN,"7.Health, pharmaceuticals, education, cultural...",CAP,NaN,...,"Bovine cattle sheep and goats horses,",2113.0,Horses asses mules and hinnies live,41,CAP,0.0,0.0,1.0,1,1To1 WITH H4
1,H5,101,"Horses, asses, mules and hinnies; live",10129,"Horses; live, other than pure-bred breeding an...",1111.0,NaN,"1.Agriculture, forestry, fishing, food, bevera...",INT,PRIMARY,...,"Bovine cattle sheep and goats horses,",2113.0,Horses asses mules and hinnies live,111,INT,1.0,0.0,0.0,1,1To1 WITH H4
2,H5,101,"Horses, asses, mules and hinnies; live",10130,Asses; live,1111.0,NaN,"1.Agriculture, forestry, fishing, food, bevera...",INT,PRIMARY,...,"Bovine cattle sheep and goats horses,",2113.0,Horses asses mules and hinnies live,111,INT,1.0,0.0,0.0,1,1To1 WITH H4
3,H5,101,"Horses, asses, mules and hinnies; live",10190,Mules and hinnies; live,1111.0,NaN,"1.Agriculture, forestry, fishing, food, bevera...",INT,PRIMARY,...,"Bovine cattle sheep and goats horses,",2113.0,Horses asses mules and hinnies live,111,INT,1.0,0.0,0.0,1,1To1 WITH H4
4,H5,102,Bovine animals; live,10221,"Cattle; live, pure-bred breeding animals",112010.0,NaN,"1.Agriculture, forestry, fishing, food, bevera...",CAP,NaN,...,"Bovine cattle sheep and goats horses,",2111.0,Bovine cattle live,41,CAP,0.0,0.0,1.0,1,1To1 WITH H4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5382,H5,9702,"Engravings, prints and lithographs; original",970200,"Engravings, prints and lithographs; original",713202.0,NaN,"7.Health, pharmaceuticals, education, cultural...",CONS,PROCESSED,...,"Manufactures nec,",38960.0,Paintings drawings and pastels; original engr...,61,CONS,0.0,1.0,0.0,1,1To1 WITH H4
5383,H5,9703,"Sculptures and statuary; original, in any mate...",970300,"Sculptures and statuary; original, in any mate...",713202.0,NaN,"7.Health, pharmaceuticals, education, cultural...",CONS,PROCESSED,...,"Manufactures nec,",38960.0,Paintings drawings and pastels; original engr...,61,CONS,0.0,1.0,0.0,1,1To1 WITH H4
5384,H5,9704,"Stamps, postage or revenue; stamp-postmarks, f...",970400,"Stamps, postage or revenue; stamp-postmarks, f...",813202.0,NaN,"8.Government, military and other",CONS,PROCESSED,...,"Machinery and equipment nec,",38960.0,Paintings drawings and pastels; original engr...,61,CONS,0.0,1.0,0.0,1,1To1 WITH H4
5385,H5,9705,Collections and collectors' pieces; of zoologi...,970500,Collections and collectors' pieces; of zoologi...,713202.0,NaN,"7.Health, pharmaceuticals, education, cultural...",CONS,PROCESSED,...,"Manufactures nec,",38960.0,Paintings drawings and pastels; original engr...,61,CONS,0.0,1.0,0.0,1,1To1 WITH H4
5386,H5,9706,Antiques; of an age exceeding one hundred years,970600,Antiques; of an age exceeding one hundred years,713202.0,NaN,"7.Health, pharmaceuticals, education, cultural...",CONS,PROCESSED,...,"Manufactures nec,",38960.0,Paintings drawings and pastels; original engr...,61,CONS,0.0,1.0,0.0,1,1To1 WITH H4

In [15]:
hs_bec=hs_bec_raw[['HS6','BEC5Code1']]
hs_bec.rename(columns={'HS6':'HS', 'BEC5Code1':'BEC'}, inplace=True)
hs_bec

/Users/ejju/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

          HS       BEC
0      10121  712010.0
1      10129    1111.0
2      10130    1111.0
3      10190    1111.0
4      10221  112010.0
...      ...       ...
5382  970200  713202.0
5383  970300  713202.0
5384  970400  813202.0
5385  970500  713202.0
5386  970600  713202.0

[5387 rows x 2 columns]

In [16]:
hs_bec.isnull().sum()#null값이 2개 있음을 확인

HS     0
BEC    2
dtype: int64

In [17]:
hs_bec[(hs_bec['BEC'].isnull())]
#https://unipass.customs.go.kr에서 검색
#71.08-금(백금을 도금한 금을 포함하며, 가공하지 않은 것ㆍ반가공한 모양이나 가루 모양인 것으로 한정,.20-화폐용
#71.18 - 주화,.90-기타

          HS  BEC
3513  710820  NaN
3542  711890  NaN

In [18]:
hs_bec = hs_bec.fillna(0)

In [19]:
hs_bec.isnull().sum()

HS     0
BEC    0
dtype: int64

In [20]:
hs_bec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5387 entries, 0 to 5386
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HS      5387 non-null   int64
 1   BEC     5387 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 84.3 KB

In [21]:
hs_bec['BEC'] =hs_bec['BEC'].astype('int64')

In [22]:
hs_bec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5387 entries, 0 to 5386
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   HS      5387 non-null   int64
 1   BEC     5387 non-null   int64
dtypes: int64(2)
memory usage: 84.3 KB

In [23]:
hs_bec.to_csv("hs_bec.csv", index = False)